### ISSUE TITLE
current status & build instructions & upstream repo?

### ISSUE THREAD

**Issue by bjuergens** [RolandTaverner/ctp2#1]
could you add a link somewhere to the upstream svn repo? 

is the current version runnable on any system? 

could you add a readme with minimal build instructions?

**Comment by RolandTaverner** [comment]
Hi. Sorry, last year my situation was FUBAR a bit so I had no time for this project.
Added README.md.

**Comment by RolandTaverner** [comment]
Current version is runnable on Windows 10 in 16-bit color compatibility mode. Not tested on something else.
